FROM ubuntu:latest
RUN apt-get update
RUN apt-get install -y nodejs npm
COPY ./package.json /
COPY ./package-lock.json /
RUN npm i
COPY ./index.js /
COPY ./localhost.crt /
COPY ./localhost.key /
EXPOSE 9443
CMD ["/bin/npm","run","start"]